# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cu_video_tracker_dialog_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(574, 312)
        Form.setMouseTracking(False)
        self.horizontalLayoutWidget = QtGui.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 261))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(400, 70, 171, 100))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lat = QtGui.QLabel(self.verticalLayoutWidget)
        self.lat.setObjectName(_fromUtf8("lat"))
        self.verticalLayout.addWidget(self.lat)
        self.lon = QtGui.QLabel(self.verticalLayoutWidget)
        self.lon.setObjectName(_fromUtf8("lon"))
        self.verticalLayout.addWidget(self.lon)
        self.E = QtGui.QLabel(self.verticalLayoutWidget)
        self.E.setObjectName(_fromUtf8("E"))
        self.verticalLayout.addWidget(self.E)
        self.N = QtGui.QLabel(self.verticalLayoutWidget)
        self.N.setObjectName(_fromUtf8("N"))
        self.verticalLayout.addWidget(self.N)
        self.video_widget = QtGui.QWidget(Form)
        self.video_widget.setEnabled(True)
        self.video_widget.setGeometry(QtCore.QRect(10, 10, 371, 261))
        self.video_widget.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.video_widget.setObjectName(_fromUtf8("video_widget"))
        self.replayPlay_pushButton = QtGui.QPushButton(Form)
        self.replayPlay_pushButton.setEnabled(False)
        self.replayPlay_pushButton.setGeometry(QtCore.QRect(480, 40, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replayPlay_pushButton.sizePolicy().hasHeightForWidth())
        self.replayPlay_pushButton.setSizePolicy(sizePolicy)
        self.replayPlay_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.replayPlay_pushButton.setMouseTracking(False)
        self.replayPlay_pushButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.replayPlay_pushButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.replayPlay_pushButton.setAcceptDrops(False)
        self.replayPlay_pushButton.setCheckable(True)
        self.replayPlay_pushButton.setChecked(False)
        self.replayPlay_pushButton.setAutoRepeat(False)
        self.replayPlay_pushButton.setAutoExclusive(False)
        self.replayPlay_pushButton.setAutoDefault(False)
        self.replayPlay_pushButton.setDefault(False)
        self.replayPlay_pushButton.setFlat(False)
        self.replayPlay_pushButton.setObjectName(_fromUtf8("replayPlay_pushButton"))
        self.addpoint_button = QtGui.QPushButton(Form)
        self.addpoint_button.setEnabled(False)
        self.addpoint_button.setGeometry(QtCore.QRect(400, 200, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addpoint_button.sizePolicy().hasHeightForWidth())
        self.addpoint_button.setSizePolicy(sizePolicy)
        self.addpoint_button.setCheckable(False)
        self.addpoint_button.setChecked(False)
        self.addpoint_button.setObjectName(_fromUtf8("addpoint_button"))
        self.Help = QtGui.QPushButton(Form)
        self.Help.setGeometry(QtCore.QRect(400, 10, 161, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Help.sizePolicy().hasHeightForWidth())
        self.Help.setSizePolicy(sizePolicy)
        self.Help.setCheckable(False)
        self.Help.setChecked(False)
        self.Help.setObjectName(_fromUtf8("Help"))
        self.replayPosition_horizontalSlider = QtGui.QSlider(Form)
        self.replayPosition_horizontalSlider.setGeometry(QtCore.QRect(10, 280, 371, 19))
        self.replayPosition_horizontalSlider.setTracking(False)
        self.replayPosition_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.replayPosition_horizontalSlider.setObjectName(_fromUtf8("replayPosition_horizontalSlider"))
        self.replayPosition_label = QtGui.QLabel(Form)
        self.replayPosition_label.setGeometry(QtCore.QRect(280, 290, 101, 21))
        self.replayPosition_label.setObjectName(_fromUtf8("replayPosition_label"))
        self.sourceLoad_pushButton = QtGui.QPushButton(Form)
        self.sourceLoad_pushButton.setGeometry(QtCore.QRect(400, 40, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sourceLoad_pushButton.sizePolicy().hasHeightForWidth())
        self.sourceLoad_pushButton.setSizePolicy(sizePolicy)
        self.sourceLoad_pushButton.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.sourceLoad_pushButton.setCheckable(False)
        self.sourceLoad_pushButton.setChecked(False)
        self.sourceLoad_pushButton.setAutoDefault(False)
        self.sourceLoad_pushButton.setDefault(True)
        self.sourceLoad_pushButton.setFlat(False)
        self.sourceLoad_pushButton.setObjectName(_fromUtf8("sourceLoad_pushButton"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(390, 230, 181, 81))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.ExporText_button = QtGui.QPushButton(self.groupBox)
        self.ExporText_button.setEnabled(False)
        self.ExporText_button.setGeometry(QtCore.QRect(10, 20, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExporText_button.sizePolicy().hasHeightForWidth())
        self.ExporText_button.setSizePolicy(sizePolicy)
        self.ExporText_button.setCheckable(False)
        self.ExporText_button.setChecked(False)
        self.ExporText_button.setObjectName(_fromUtf8("ExporText_button"))
        self.ExporShp_button = QtGui.QPushButton(self.groupBox)
        self.ExporShp_button.setEnabled(False)
        self.ExporShp_button.setGeometry(QtCore.QRect(90, 20, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExporShp_button.sizePolicy().hasHeightForWidth())
        self.ExporShp_button.setSizePolicy(sizePolicy)
        self.ExporShp_button.setCheckable(False)
        self.ExporShp_button.setChecked(False)
        self.ExporShp_button.setObjectName(_fromUtf8("ExporShp_button"))
        self.ExporSqlite_button = QtGui.QPushButton(self.groupBox)
        self.ExporSqlite_button.setEnabled(False)
        self.ExporSqlite_button.setGeometry(QtCore.QRect(10, 50, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExporSqlite_button.sizePolicy().hasHeightForWidth())
        self.ExporSqlite_button.setSizePolicy(sizePolicy)
        self.ExporSqlite_button.setCheckable(False)
        self.ExporSqlite_button.setChecked(False)
        self.ExporSqlite_button.setObjectName(_fromUtf8("ExporSqlite_button"))
        self.ExporKML_button = QtGui.QPushButton(self.groupBox)
        self.ExporKML_button.setEnabled(False)
        self.ExporKML_button.setGeometry(QtCore.QRect(90, 50, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExporKML_button.sizePolicy().hasHeightForWidth())
        self.ExporKML_button.setSizePolicy(sizePolicy)
        self.ExporKML_button.setCheckable(False)
        self.ExporKML_button.setChecked(False)
        self.ExporKML_button.setObjectName(_fromUtf8("ExporKML_button"))
        self.replay_mapTool_pushButton = QtGui.QPushButton(Form)
        self.replay_mapTool_pushButton.setGeometry(QtCore.QRect(400, 170, 161, 23))
        self.replay_mapTool_pushButton.setCheckable(True)
        self.replay_mapTool_pushButton.setObjectName(_fromUtf8("replay_mapTool_pushButton"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.lat.setText(_translate("Form", "Latitude : ", None))
        self.lon.setText(_translate("Form", "Longitude :", None))
        self.E.setText(_translate("Form", "Easting :", None))
        self.N.setText(_translate("Form", "Northing : ", None))
        self.replayPlay_pushButton.setText(_translate("Form", "Play/Pause", None))
        self.addpoint_button.setText(_translate("Form", "Add Point", None))
        self.Help.setText(_translate("Form", "Help", None))
        self.replayPosition_label.setText(_translate("Form", "-:- / -:-", None))
        self.sourceLoad_pushButton.setText(_translate("Form", "Open...", None))
        self.groupBox.setTitle(_translate("Form", "Export to", None))
        self.ExporText_button.setText(_translate("Form", "Text", None))
        self.ExporShp_button.setText(_translate("Form", "Shapefile", None))
        self.ExporSqlite_button.setText(_translate("Form", "Sqlite DB", None))
        self.ExporKML_button.setText(_translate("Form", "KML", None))
        self.replay_mapTool_pushButton.setText(_translate("Form", "Map tool", None))

